fail_fast: true
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
    - id: trailing-whitespace
      exclude: ^dind/templates/configmap.yaml$
    - id: end-of-file-fixer
    - id: mixed-line-ending
    - id: check-added-large-files
